security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /
                # always_remember_me: true

    access_control:
        # Zone admin uniquement pour ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Zones accessibles à tous les utilisateurs connectés
        - { path: ^/planning, roles: ROLE_USER }
        - { path: ^/chantier, roles: ROLE_USER }
        - { path: ^/personnel, roles: ROLE_USER }

        # Pages User++ uniquement
        - { path: ^/userpp, roles: ROLE_USERPP }

        # Pages User (classique et ++)
        - { path: ^/user, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
